---
# cf. https://www.digitalocean.com/community/tutorials/how-to-install-couchdb-and-futon-on-ubuntu-14-04
- name: add couchdb stable repo
  apt_repository:
    repo: ppa:couchdb/stable
    state: present
    update_cache: yes

- name: install couchdb
  apt:
    name: couchdb
    state: present

- name: listen on all interfaces 
  ini_file:
    dest: /etc/couchdb/local.ini
    section: httpd
    option: bind_address
    value: 0.0.0.0

- name: start couchdb
  service:
    name: couchdb
    state: started

- name: create couch admin user
  uri:
    url: http://localhost:5984/_config/admins/couch
    method: PUT
    body: '"123"'

#- name: create faucet database
#  uri:
#    url: http://localhost:5984/faucet
#    method: PUT
#    user: couch
#    password: 123
#    force_basic_auth: yes
#    # cf. http://docs.couchdb.org/en/2.0.0/api/database/common.html
#    status_code: 201


- name: set require_valid_user = true 
  ini_file:
    dest: /etc/couchdb/local.ini
    section: couch_httpd_auth 
    option: require_valid_user
    value: 'true'

- name: configure http authentication
  lineinfile:
    dest: /etc/couchdb/local.ini
    regexp: '^WWW-Authenticate'
    insertafter: '^;WWW-Authenticate'
    line: 'WWW-Authenticate = Basic realm="administrator"'

- name: restart couchdb
  service:
    name: couchdb
    state: restarted


