---
# cf. https://www.digitalocean.com/community/tutorials/how-to-install-couchdb-and-futon-on-ubuntu-14-04
- name: add couchdb stable repo
  apt_repository:
    repo: ppa:couchdb/stable
    state: present
    update_cache: yes

- name: install couchdb
  apt:
    name: couchdb
    state: present

- name: listen on all interfaces 
  ini_file:
    dest: /etc/couchdb/local.ini
    section: httpd
    option: bind_address
    value: 0.0.0.0

- name: set require_valid_user = true 
  ini_file:
    dest: /etc/couchdb/local.ini
    section: couch_httpd_auth 
    option: require_valid_user
    value: 'true'

- name: configure http authentication
  lineinfile:
    dest: /etc/couchdb/local.ini
    regexp: '^WWW-Authenticate'
    insertafter: '^;WWW-Authenticate'
    line: 'WWW-Authenticate = Basic realm="administrator"'

- name: set require_valid_user = true 
  ini_file:
    dest: /etc/couchdb/local.ini
    section: admins
    option: couch
    value: 123

- name: restart couchdb
  service:
    name: couchdb
    state: restarted

