---
- name: install pip
  apt:
    name: python-pip
    state: latest
  when: not using_python3

- name: install pip3
  apt:
    name: python3-pip
    state: latest
  when: using_python3

- name: upgrade pip
  pip:
    name: pip
    state: latest

- name: install virtualenv
  pip:
    name: virtualenv
    state: latest

#  - name: install virtualenvwrapper
#    pip:
#      name: virtualenvwrapper


