---
- user:
    name: faucet

- name: add faucet to sudoers
  lineinfile:
    dest: /etc/sudoers.d/faucet
    line: "faucet ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
    mode: 0440
    validate: visudo -cf %s

- name: checkout faucet
#  become_user: faucet
  git:
    clone: yes
    dest: ~faucet/faucet
    repo: https://github.com/REANNZ/faucet.git

- name: set faucet repo owner to faucet user
  file:
    dest: ~faucet/faucet
    owner: faucet
    group: faucet
    recurse: yes

- name: create faucet config dir
  file:
    path: /etc/faucet
    state: directory

- name: create faucet log dir
  file:
    path: /var/log/faucet
    state: directory
    owner: faucet
    group: faucet

- name: create /etc/faucet/faucet-environment.sh
  copy:
    src: etc/faucet/faucet-environment.sh
    dest: /etc/faucet/faucet-environment.sh
    owner: root
    group: root
    mode: 0755

- name: create /etc/faucet/faucet.yml
  copy:
    src: etc/faucet/faucet.yml
    dest: /etc/faucet/faucet.yml
    owner: root
    group: root
    mode: 0644

- name: create /etc/faucet/ryu.conf
  copy:
    src: etc/faucet/ryu.conf
    dest: /etc/faucet/ryu.conf
    owner: root
    group: root
    mode: 0644

- name: create faucet.service
  copy:
    src: etc/systemd/system/faucet.service
    dest: /etc/systemd/system/faucet.service
    owner: root
    group: root
    mode: 0644

- name: create ~faucet/start-faucet.sh
  copy:
    src: start-faucet.sh
    dest: ~faucet/start-faucet.sh
    owner: faucet
    group: faucet
    mode: 0755

- name: init faucet virtenv
#  become_user: faucet
  pip:
    requirements: ~faucet/faucet/requirements.txt
    virtualenv: ~faucet/virtenv

- name: add faucet to virtenv
#  shell:
#    "source ~faucet/virtenv/bin/activate; pip install -e ~faucet/faucet"
  pip:
    virtualenv: ~faucet/virtenv
    editable: yes
    chdir: ~faucet/faucet
    name: "."
    state: present

- name: set virtenv owner to faucet user
  file:
    dest: ~faucet/virtenv
    owner: faucet
    group: faucet
    recurse: yes

- name: (re)start faucet service
  systemd:
    state: restarted
    daemon_reload: yes
    name: faucet
    enabled: yes
