---
- hosts: all
  gather_facts: false

  tasks:
  - name: install python 2
    become: true
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: install virtualbox and vagrant
    become: true
    action: apt pkg={{item}} state=installed
    with_items:
      - virtualbox
      - vagrant

  - name: install wireshark
    become: true
    apt:
      name: wireshark
      state: installed

  - name: setuid dumpcap
    become: true
    file:
      path: /usr/bin/dumpcap
      owner: root
      group: root
      mode: 04755 

