---
- hosts: vagrant
  become: true
  gather_facts: false

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: install virtualbox and vagrant
    action: apt pkg={{item}} state=installed
    with_items:
      - virtualbox
      - vagrant

  - name: install wireshark
    apt:
      name: wireshark
      state: installed

  - name: setuid dumpcap
    file:
      path: /usr/bin/dumpcap
      owner: root
      group: root
      mode: 04755 

