---

# install openvswitch & related
- hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: update apt cache
    apt:
      update_cache: true

  - name: install openvswitch
    action: apt pkg={{item}} state=latest
    with_items:
      - openvswitch-common
      - openvswitch-switch

  - name: install wireshark
    apt:
      name: wireshark
      state: installed

  - name: setuid dumpcap
    file:
      path: /usr/bin/dumpcap
      owner: root
      group: root
      mode: 04755 


# install virtualization environments
- hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: add virtualbox repo key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
      validate_certs: no


  - name: add virtualbox dist repo and get latest
    apt_repository:
      repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
      state: present 
      filename: virtualbox
      update_cache: yes

  - name: update apt cache
    apt:
      update_cache: true
 
  - name: install virtualbox and vagrant
    action: apt pkg={{item}} state=latest
    with_items:
      - virtualbox
      - vagrant

# install python tools
- hosts: all
  become: true
  gather_facts: true

  tasks:
  - name: update apt cache
    apt:
      update_cache: true

  - name: install pip
    apt:
      name: python-pip
      state: latest

  - name: upgrade pip
    pip:
      name: pip
      state: latest

  - name: install virtualenv
    pip:
      name: virtualenv
      state: latest

#  - name: install virtualenvwrapper
#    pip:
#      name: virtualenvwrapper



