---
- name: add nginx repo key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: add nginx repo
  apt_repository:
    repo: deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx

- name: install nginx package
  apt:
    name: nginx
    state: installed
    update_cache: true

