---
- user:
    name: faucet

- name: add faucet to sudoers
  lineinfile:
    dest: /etc/sudoers.d/faucet
    line: "faucet ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
    mode: 0440
    validate: visudo -cf %s

- name: checkout faucet
#  become_user: faucet
  git:
    clone: yes
    dest: ~faucet/faucet
    repo: https://github.com/REANNZ/faucet.git

- name: set faucet repo owner to faucet user
  file:
    dest: ~faucet/faucet
    owner: faucet
    group: faucet
    recurse: yes

- name: /etc/opt/faucet
  file:
    path: /etc/opt/faucet
    state: directory

- name: /var/log/faucet
  file:
    path: /var/log/faucet
    state: directory
    owner: faucet
    group: faucet

- name: create /etc/default/faucet
  copy:
    src: etc_default_faucet
    dest: /etc/default/faucet
    owner: root
    group: root
    mode: 0644

- name: create /etc/opt/faucet/faucet.yml
  copy:
    src: faucet.yml
    dest: /etc/opt/faucet/faucet.yml
    owner: root
    group: root
    mode: 0644

- name: create ~faucet/start-faucet.sh
  copy:
    src: start-faucet.sh
    dest: ~faucet/start-faucet.sh
    owner: faucet
    group: faucet
    mode: 0755

- name: init faucet virtenv
#  become_user: faucet
  pip:
    requirements: ~faucet/faucet/requirements.txt
    virtualenv: ~faucet/virtenv

- name: set virtenv owner to faucet user
  file:
    dest: ~faucet/virtenv
    owner: faucet
    group: faucet
    recurse: yes








