---
- name: add virtualbox repo key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    validate_certs: no

- name: add virtualbox dist repo and get latest
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present 
    filename: virtualbox
    update_cache: yes

- name: update apt cache
  apt:
    update_cache: true
 
- name: install virtualbox and vagrant
  action: apt pkg={{item}} state=latest
  with_items:
    - virtualbox
    - vagrant


