---
- name: add postgres repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    filename: pgdg

- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: update apt cache
  apt:
    update_cache: true

- name: install postgres packages
  apt: name={{item}} state=installed
  with_items:
    - postgresql-9.6
    - libpq-dev
