---
- name: install wireshark
  apt:
    name: wireshark
    state: installed

- name: setuid dumpcap
  file:
    path: /usr/bin/dumpcap
    owner: root
    group: root
    mode: 04755 

- name: enable X11 forwarding
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "X11Forwarding yes"
    state: present
  notify:
  - restart sshd

