---
# - name: copy ovs config script
#   copy:
#     src: ovs-setup.sh
#     dest: /root/ovs-setup.sh
#     owner: root
#     group: root
#     mode: 0755
# 
# - name: copy ovs config script
#   copy:
#     src: qemu-system.sh
#     dest: /root/qemu-system.sh
#     owner: root
#     group: root
#     mode: 0755
# 
# 
# - name: copy vagrant vm config
#   copy:
#     src: Vagrantfile
#     dest: /root/Vagrantfile
#     owner: root
#     group: root
#     mode: 0644

- name: install ovs setup helper script
  template:
    src: ovs-setup.sh.j2
    dest: /root/ovs-setup.sh
    owner: root
    group: root
    mode: 0755

- name: run ovs setup helper script
  shell: /root/ovs-setup.sh

- name: install qemu-ifup/down
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - qemu-ifup
    - qemu-ifdown

- name: create /images directory
  file:
    path: /images
    state: directory
    mode: 0755
    owner: root
    group: root
 
- name: check if base os image is already present
  stat:
    path: /images/debian_wheezy_amd64_standard.qcow2
  register: base_image

- name: download base os image
  get_url:
    url:  https://people.debian.org/~aurel32/qemu/amd64/debian_wheezy_amd64_standard.qcow2
    dest: /images
    owner: root
    group: root
    mode: 0644
  when: base_image.stat.exists == False

# - name: copy geant guest network config
#   copy:
#     src: geant-guest.conf
#     dest: /etc/wpa_supplicant/geant-guest.conf
#     owner: root
#     group: root
#     mode: 0644

- include: vm.yml
  vars:
    vm_name: faucet
    vnc_idx: 1

- include: vm.yml
  vars:
    vm_name: gauge
    vnc_idx: 2


#- name: configure lan interface
#  template:
#    src: ethernet-interface.j2
#    dest: /etc/network/interfaces.d/lan-interface



