---
# - name: copy ovs config script
#   copy:
#     src: ovs-setup.sh
#     dest: /root/ovs-setup.sh
#     owner: root
#     group: root
#     mode: 0755
# 
# - name: copy ovs config script
#   copy:
#     src: qemu-system.sh
#     dest: /root/qemu-system.sh
#     owner: root
#     group: root
#     mode: 0755
# 
# 
# - name: copy vagrant vm config
#   copy:
#     src: Vagrantfile
#     dest: /root/Vagrantfile
#     owner: root
#     group: root
#     mode: 0644

- name: install qemu-ifup/down
  copy:
    src: "{{ item }}"
    dest: /etc
    owner: root
    group: root
    mode: 0755
  with_items:
    - qemu-ifup
    - qemu-ifdown

- name: create /images directory
  file:
    path: /images
    state: directory
    mode: 0755
    owner: root
    group: root
 
- name: check if base os image is already present
  stat:
    path: /images/debian_wheezy_amd64_standard.qcow2
  register: base_image

- name: download base os image
  get_url:
    url:  https://people.debian.org/~aurel32/qemu/amd64/debian_wheezy_amd64_standard.qcow2
    dest: /images
    owner: root
    group: root
    mode: 0644
  when: base_image.stat.exists == False

# - name: copy geant guest network config
#   copy:
#     src: geant-guest.conf
#     dest: /etc/wpa_supplicant/geant-guest.conf
#     owner: root
#     group: root
#     mode: 0644
 
- name: create faucet vm startup script
  template:
    src: qemu-startup.sh.j2
    dest: /root/faucet-startup.sh
    mode: 0755
    owner: root
    group: root
  vars:
    vm_name: faucet
    vnc_idx: 1

- name: create faucet vm service config
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/faucet.service
    mode: 0644
    owner: root
    group: root
  vars:
    vm_name: faucet
    exec_start: /root/faucet-startup.sh


- name: create gauge vm startup script
  template:
    src: qemu-startup.sh.j2
    dest: /root/gauge-startup.sh
    mode: 0755
    owner: root
    group: root
  vars:
    vm_name: gauge
    vnc_idx: 2

- name: create gauge vm service config
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/gauge.service
    mode: 0644
    owner: root
    group: root
  vars:
    vm_name: gauge
    exec_start: /root/gauge-startup.sh



#- name: configure lan interface
#  template:
#    src: ethernet-interface.j2
#    dest: /etc/network/interfaces.d/lan-interface



