---
- name: copy ovs config script
  copy:
    src: ovs-setup.sh
    dest: /root/ovs-setup.sh
    owner: root
    group: root
    mode: 0755

- name: copy ovs config script
  copy:
    src: qemu-system.sh
    dest: /root/qemu-system.sh
    owner: root
    group: root
    mode: 0755


- name: copy vagrant vm config
  copy:
    src: Vagrantfile
    dest: /root/Vagrantfile
    owner: root
    group: root
    mode: 0644

- name: install qemu-ifup/down
  copy:
    src: "{{ item }}"
    dest: /etc
    owner: root
    group: root
    mode: 0755
  with_items:
    - qemu-ifup
    - qemu-ifdown

- name: create /images directory
  file:
    path: /images
    state: directory
    mode: 0755
    owner: root
    group: root
  
#- name: download debian_wheezy_amd64_standard.qcow2
#  get_url:
#    url:  https://people.debian.org/~aurel32/qemu/amd64/debian_wheezy_amd64_standard.qcow2
#    dest: /images
#    owner: root
#    group: root
#    mode: 0644

