---
- name: install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: add internet2 repo rpm
  yum:
    name: http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/Internet2-repo-0.7-1.noarch.rpm
    state: present

- name: install perfSONAR testpoint
  yum:
    name: perfsonar-testpoint
    state: present

- name: install perfSONAR toolkit
  yum:
    name: perfsonar-toolkit
    state: present
  tags:
    - toolkit

