---

- debug:
    msg: "ansible_distribution '{{ ansible_distribution }}', ansible_distribuion_release '{{ ansible_distribution_release }}', ansible_distribution_version '{{ ansible_distribution_version }}'"

- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: debian.yml
  when: ansible_distribution == "Debian"
